[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kryptpay = "6k73LWhMtLhJLVyC3qQGa8pvDZ2GUXnLAb9n3juk8u3A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/gloryagatevure/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
