[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
kryptpay = "7KSFNXrjkYoHbWj7YBV1kXCabY7kTnFB6VNNDAX83fbc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gloryagatevure/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
